print('ÒÅÑÒ' )
st1=input()
print('Enter the age of animal' )
st2=input()
print("Enter the animal's nickname" )
st3=input()
print('Òåñò' )
st4=input()
print('Enter the age of animal' )
st5=input()
print("Enter the animal's nickname" )
st6=input()

print()

